apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: "openshift-config"

generatorOptions:
  disableNameSuffixHash: true

resources:
  - api-domain-tls.yaml
  - api-domain-tls-cert.yaml